### PR TITLE
Feature/notebook with pytorch training and tensorboard

### PR DESCRIPTION
**Pull request by hsteude**
This PR adds a PyTorch training example using a Variational Autoencoder (VAE) for generating MNIST images. The main objectives are:
1. Demonstrating the feasibility of using Kubeflow notebooks as python IDEs for development.
2. Illustrating the use of TensorBoard within Kubeflow by creating a new instance linked to the PVC of the training notebook.

**Testing Procedure:**
1. Initiate a new notebook instance (preferably with the code server Python image).
2. Clone this repository.
3. Go to the `kf-notebook/mnist` directory.
4. Follow the setup instructions in the README. (Python 3.9 is required for the `poetry install`, which can be installed in a  Conda env in the Kubeflow notebook.)
5. Execute the steps and confirm operational functionality.

### CODE REVIEW

**Comment by samoturk** [comment]
I added a commit fixing two minor issues. Is there a reason you created a `kf-notebooks` folder instead of putting this in `notebooks`?

**Comment by hsteude** [comment]
@samoturk : Thanks!
The reason I put it into kf-notebooks is a) that I want to show that kf-notebooks are more that what people think of when they hear "notebook" (in most cases Jupyter notebook I assume) and b) that I plan to also describe how to set up demonstration UIs using dash or streamlit in this directory.

**Comment by samoturk** [comment]
Notebook tab in KF UI shows all types notebooks not just Jupyter, so in Kubeflow context notebook is broader concept anyway. Your call :)

**Comment by hsteude** [comment]
Alright, you seem to have a stronger opinion. So I disagree and commit ;)

**Pull request merged**
